nome = input('Qual o seu nome completo? ').strip()
print('Analisando o seu nome eu concluo que...')
print(nome.upper())
print(nome.lower())
print('Seu nome tem, ao todo, {} letras!'.format(len(nome.replace(' ', ''))))
print('Seu primeiro nome é {} e ele tem {} letras!.'.format(nome.split()[0], len(nome.split()[0])))
